name: tinder_with_chuck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_analytics: ^10.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3  
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.0
  flutter_launcher_icons: ^0.13.1
  hive_generator:

flutter_launcher_icons:
  image_path: "assets/images/chuck.png"
  android: "launcher_icon"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

