name: tinder_with_chuck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3  
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/chuck.jpg
